[package]
name = "playing-with-tokio"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
tokio = { version = "1", features = ["full", "time", "test-util", "tracing"] }
tracing-subscriber = { version = "0.3", features = ["fmt"] }
tracing = "*"